# Generated by Django 4.2.24 on 2025-09-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_updated_on')
    ]

    operations = [
    ]
