# Generated by Django 4.2.24 on 2025-09-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
    ]
